'use strict';

module.exports = () => {
  const { winners, tests } = require('./getDataTests')();

  const data1 = [0];
  const data2 = [0];
  winners.forEach((e, index) => {
    if(e === '1') {
      data1.push(data1[index]+1);
      data2.push(data2[index]);
    } else {
      data1.push(data1[index]);
      data2.push(data2[index]+1);
    }
  });

  return [
    '<!doctype html>',
    '<html>',
    '<head>',
    '  <title>Line Styles</title>',
    '  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.6.0/Chart.min.js"></script>',
    '  <style>',
    '    canvas{',
    '      -moz-user-select: none;',
    '      -webkit-user-select: none;',
    '      -ms-user-select: none;',
    '    }',
    '  </style>',
    '</head>',
    '<body>',
    '<div style="width:75%;">',
    '  <canvas id="canvas"></canvas>',
    '</div>',
    '<script>',
    '  const config = {',
    '    type: "line",',
    '    data: {',
    `      labels: [${tests}],`,
    '      datasets: [',
    '        {',
    '          label: "1\'s victories",',
    '          fill: false,',
    '          lineTension: 0.1,',
    '          borderCapStyle: "butt",',
    '          borderDash: [],',
    '          borderDashOffset: 0.0,',
    '          borderJoinStyle: "miter",',
    '          pointBorderWidth: 1,',
    '          pointHoverRadius: 5,',
    '          pointHoverBorderWidth: 2,',
    '          pointRadius: 5,',
    '          pointHitRadius: 10,',
    '          backGroundColor: "rgba(75,192,192,0.4)",',
    '          borderColor: "rgba(75,192,192,1)",',
    '          pointBorderColor: "rgba(75,192,192,1)",',
    '          pointBackgroundColor: "#fff",',
    '          pointHoverBackgroundColor: "rgba(75,192,192,1)",',
    '          pointHoverBorderColor: "rgba(220,220,220,1)",',
    `          data: [${data1}]`,
    '        },',
    '        {',
    '          label: "2\'s victories",',
    '          fill: false,',
    '          lineTension: 0.1,',
    '          borderCapStyle: "butt",',
    '          borderDash: [],',
    '          borderDashOffset: 0.0,',
    '          borderJoinStyle: "miter",',
    '          pointBorderWidth: 1,',
    '          pointHoverRadius: 5,',
    '          pointHoverBorderWidth: 2,',
    '          pointRadius: 5,',
    '          pointHitRadius: 10,',
    '          backGroundColor: "rgba(180,192,192,0.4)",',
    '          borderColor: "rgba(180,192,192,1)",',
    '          pointBorderColor: "rgba(180,192,192,1)",',
    '          pointBackgroundColor: "#fff",',
    '          pointHoverBackgroundColor: "rgba(180,192,192,1)",',
    '          pointHoverBorderColor: "rgba(180,220,220,1)",',
    `          data: [${data2}]`,
    '        },',
    '      ]',
    '    },',
    '    options: {',
    '      responsive: true,',
    '      title: {',
    '        display: true,',
    '        text: "Chart.js Line Chart"',
    '      },',
    '      tooltips: {',
    '        mode: "index",',
    '        intersect: false,',
    '      },',
    '      hover: {',
    '        mode: "nearest",',
    '        intersect: true',
    '      },',
    '      scales: {',
    '        xAxes: [{',
    '          display: true,',
    '          scaleLabel: {',
    '            display: true,',
    '            labelString: "Number of tests"',
    '          }',
    '        }],',
    '        yAxes: [{',
    '          display: true,',
    '          scaleLabel: {',
    '            display: true,',
    '            labelString: "Number of victories"',
    '          }',
    '        }]',
    '      }',
    '    }',
    '  };',
    '  window.onload = function() {',
    '    const ctx = document.getElementById("canvas").getContext("2d");',
    '    window.myLine = new Chart(ctx, config);',
    '  };',
    '</script>',
    '</body>',
    '</html>'
  ].join('\n');
};
